### PR TITLE
fix(dashboard): don't open with startup option args

### LINKED ISSUE #221: bug(dashboard): error when starting neovim with an Octo command
### Did you check docs and existing issues?

- [X] I have read all the snacks.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of snacks.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.2 Build type: Release LuaJIT 2.1.1713484068

### Operating system/version

Pop!_OS 22.04 LTS x86_64

### Describe the bug

I get the following error when running `nvim +'Octo issue edit 1'` with dashboard enabled:

```log
Error executing vim.schedule lua callback: ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:94: Error executing lua: .../data/nvim/lazy/octo.nvim/lua/octo/model/octo-buffer.lua:78:
 Buffer is not 'modifiable'
stack traceback:
        [C]: in function 'nvim_buf_set_lines'
        .../data/nvim/lazy/octo.nvim/lua/octo/model/octo-buffer.lua:78: in function 'clear'
        .../data/nvim/lazy/octo.nvim/lua/octo/model/octo-buffer.lua:100: in function 'render_issue'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:272: in function 'create_buffer'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:95: in function <...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:94>
        [C]: in function 'nvim_buf_call'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:94: in function 'cb'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:133: in function 'cb'
        ...tem/.repro/data/nvim/lazy/octo.nvim/lua/octo/gh/init.lua:163: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
stack traceback:
        [C]: in function 'nvim_buf_call'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:94: in function 'cb'
        ...system/.repro/data/nvim/lazy/octo.nvim/lua/octo/init.lua:133: in function 'cb'
        ...tem/.repro/data/nvim/lazy/octo.nvim/lua/octo/gh/init.lua:163: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

### Steps To Reproduce

1. [Install `gh`](https://github.com/cli/cli#installation) and run `gh auth login`
2. Save the minimal init below as `repro.lua`
3. Run `nvim -u repro.lua`
4. Press `q` once the plugins are installed and the dashboard is displayed
5. Run the following command in shell to copy your gh token to the repro env: `cp -r ~/.config/gh ./.repro/config/`
6. Run `nvim -u repro.lua +'Octo issue edit 1'`
7. You should see the error above
8. Disabling snack's dashboard will prevent the error

### Expected Behavior

I expect dashboard to not cause an error when following the repro steps above. Let me know if I should log an issue to `octo.nvim` instead. Thanks!

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/snacks.nvim", opts = { dashboard = { enabled = true } } },
    { "pwntester/octo.nvim", opts = {} },
    { "nvim-telescope/telescope.nvim", opts = {} },
    { "nvim-lua/plenary.nvim", lazy = true },
  },
})
```

### PR DESCRIPTION
**Pull request by dpetka2001**
## Description
Don't open dashboard when Neovim opens with only startup option args. Took a look at how `dashboard.nvim` did it.
They also have an autocmd for `StdInReadPre`, but I tested with piping `echo "hello" | nvim` and it works as expected.

Not sure if it's the best solution, so feel free to make any additional changes or completely disregard for something more robust.

## Related Issue(s)
Closes #221.

### CODE REVIEW

File: lua/snacks/dashboard.lua [hunk 1]
```diff
@@ -1084,6 +1084,12 @@ function M.setup()
     return
   end
 
+  -- don't open dashboard if Neovim was invoked for example `nvim +'Octo issue edit 1'`
+  if vim.fn.argc(-1) == 0 and vim.api.nvim_buf_get_name(0) ~= "" then
```
Comment (folke) [inline lua/snacks/dashboard.lua:1088]: can you remove the argc check here? That's already handled.
Just checking bufname is enough

**Comment by folke** [comment]
I snacks I don't need the STdInPre event. I simply check the uis and see if stdin is not a tty instead

File: lua/snacks/dashboard.lua (hunk 1 above)
Comment (dpetka2001) [reply lua/snacks/dashboard.lua]: Done. Just out of curiosity where is this handled? Because I only see `argc(-1) > 0` in the lines above. Just so I can understand better if you don't mind.

File: lua/snacks/dashboard.lua [hunk 2]
```diff
@@ -1084,6 +1084,12 @@ function M.setup()
     return
   end
 
+  -- don't open dashboard if Neovim was invoked for example `nvim +'Octo issue edit 1'`
+  if vim.api.nvim_buf_get_name(0) ~= "" then
+    M.status.reason = "Opened with only startup option arguments"
```
[the remark this answers is not in the document]
Comment (dpetka2001) [reply lua/snacks/dashboard.lua]: Done. Not considered nitpicking by me. No prob at all.

File: lua/snacks/dashboard.lua (hunk 1 above)
Comment (dpetka2001) [reply lua/snacks/dashboard.lua]: I see. Thanks for clarifying :smile:

**Comment by folke** [comment]
ty!
